// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'ap-southeast-1:1b46a1a3-b2cd-4e4a-b8c1-e8d7f1924b3d',
    'aws_cognito_region': 'ap-southeast-1',
    'aws_mobile_analytics_app_id': 'b4a22da072964d3fbab5eb46f46dc243',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'a85add5f-a6b3-4a33-b62f-6a3875e9421b',
    'aws_project_name': 'Viato',
    'aws_project_region': 'ap-southeast-1',
    'aws_resource_name_prefix': 'viato-mobilehub-298302908',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'ap-southeast-1_EtzUAyLp6',
    'aws_user_pools_web_client_id': '6kedemunlp7203ajv6q9q60snv',
}

export default awsmobile;
